name: container-build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log into registery
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,enable={{ is_default_branch }},priority=10

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          file: docker/Dockerfile
          tags: |
            ${{ steps.metadata.outputs.tags }}
